# Generated by Django 5.0.7 on 2024-08-03 14:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('license_id', models.CharField(max_length=255, unique=True)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('current_occupancy', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('current_occupancy', models.IntegerField(default=0)),
                ('operational_status', models.CharField(choices=[('operational', 'Operational'), ('under_maintenance', 'Under Maintenance'), ('closed', 'Closed')], default='operational', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=255, unique=True)),
                ('weight', models.IntegerField()),
                ('status', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing'), ('waiting', 'Waiting'), ('docked', 'Docked')], default='waiting', max_length=20)),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walmart.driver')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walmart.parkinglot')),
            ],
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='trucks',
            field=models.ManyToManyField(related_name='parking_lots', to='walmart.truck'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walmart.warehouse'),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walmart.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('last_restocked', models.DateTimeField(default=django.utils.timezone.now)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='walmart.warehouse')),
            ],
        ),
    ]
